### ISSUE TITLE
Support choco-solvers limitTime options (some more possible future work)

### ISSUE THREAD

**Issue by toeklk** [gsdlab/chocosolver#11]
For large (optimization) problems, it would be nice if the user could pass a maximal search time to clafer(choco)(IG).  This seems to be supported by choco (http://choco-solver.org/apidocs/org/chocosolver/solver/search/loop/monitors/SearchMonitorFactory.html#limitTime-org.chocosolver.solver.Solver-long-)

**Comment by JLiangWaterloo** [comment]
Thanks for the feature request. It's now implemented in the develop branch.

ClaferSearch::limitTime will timeout the search after the given time limit.

For example:

```java
solver.limitTime(1000);
try {
    solver.find();
} catch (ReachedLimitBestKnownException rle) {
    // This is an optimization problem and 1000ms has passed.
    // Although the solver did not complete, it returned the best known
    // (but possibly non-optimal) instance after 1000ms. This instance is
    // stored in the rle exception.
} catch (ReachedLimitException rle) {
    // 1000ms has passed.
}
```

This is only available through the API at the moment. I've also filed [this bug report](https://github.com/chocoteam/choco3/issues/297) with the Choco library that may affect the accuracy of the timeout.
