### ISSUE TITLE
Question serialisation of InstanceClafer class.

### ISSUE THREAD

**Issue by chrismcgraw60** [gsdlab/chocosolver#33]
hi,

Thanks for this really interesting project.  This is a question more than an issue.

I see that utilities are provided to output a String representation of an InstanceClafer Java object. However I can't see any API for parsing such a string representation so that I can round-trip an InstanceClafer back to a Java object from a String ( or any other kind of input format).

Am I missing something? Is there a way I can achieve this use case?  

Thanks again.

**Comment by JLiangWaterloo** [comment]
Hello Chris,

You are not missing anything. There wasn't a need for a Java InstanceClafer parser hence one was never written.

**Comment by chrismcgraw60** [comment]
hi Jimmy, ok, thanks for clarifying.
